apiVersion: v1
kind: Service
metadata:
  name: mongodb-relational-migrator
spec:
  type: NodePort  # Change to LoadBalancer if using a cloud provider
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000  # Optional
  selector:
    app: migrator
